#!/usr/bin/env bash
# Configure HAproxy to automatically redirect HTTP traffic to HTTPS.


global
    ssl-default-bind-options ssl-min-ver TLSv1.2

frontend tocvictechnology_frontend
	bind *:80
	bind *:443 ssl crt /etc/haproxy/certs/tocvictechnology.tech.pem
	http-request redirect scheme https code 301 unless { ssl_fc }
	default_backend tocvictechnology_backend

backend tocvictechnology_backend
	balance roundrobin
	server 151204-web-01 34.229.254.166:80 check
	server 151204-web-02 54.237.98.37:80 check
