#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine to respect above 
# requirements (this script w

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
