#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine to respect above 
# requirements (this script will be run on the server itself)
STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECT" "$FILE"
service nginx restart
