#!/usr/bin/env bash
# Displays `Holberton School` 10 times and `Hi` on 9th iteration

i=1
while (( i<=10 )); do
	if (( i==9 )); then
		echo -e "Holberton School\nHi"
	else
		echo "Holberton School"
	fi

	i=$((i+1))
done
