#!/usr/bin/env bash
#A bash script that prints Best School with conditions

var=1
while [[ $var -le 20 ]]
do
    case $var in
	    4)
        echo "$var"
        echo "bad luck from China"
	;;
            9)
        echo "$var"
        echo "bad luck from Japan"
	;;
            17)
        echo "$var"
        echo "bad luck from Italy"
	;;
	*)
        echo "$var"
    esac
    (( var++ ))
done
