#!/usr/bin/env bash
# Prints every minute for all 12 hours

hr=0
while (( hr <= 12 )); do
    echo "Hour: $hr"

    min=1
    while (( min < 60 )); do
	echo $min
	min=$(( min+=1 ))
    done

    hr=$(( hr+=1 ))
done
